# .github/release.yml

changelog:
  categories:
    - title: Features
      labels:
        - feature
    - title: Bugfixes
      labels:
        - bug
    - title: Non-functional
      labels:
        - non-functional
    - title: Other Changes
      labels:
        - "*"
