apiVersion: v1
kind: ConfigMap
metadata:
  name: aro-nginx-config 
  namespace: aro
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/app/public/;
        index index.php;

        server_name _;

        location / {
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_index index.php;
          fastcgi_buffers 16 16k;
          fastcgi_buffer_size 32k;
          fastcgi_param SCRIPT_FILENAME $document_root/index.php;
          #fixes timeouts
          fastcgi_read_timeout 600;
          include fastcgi_params;
        }
      }
    }